// <auto-generated />
using HW__10_Advanced_databases_with_EF_Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW__10_Advanced_databases_with_EF_Core.Migrations
{
    [DbContext(typeof(SoccerDBContext))]
    partial class SoccerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW__10_Advanced_databases_with_EF_Core.Models.SoccerPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SoccerTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoccerTeamId");

                    b.ToTable("SoccerPlayers");
                });

            modelBuilder.Entity("HW__10_Advanced_databases_with_EF_Core.Models.SoccerTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SoccerTeams");
                });

            modelBuilder.Entity("HW__10_Advanced_databases_with_EF_Core.Models.SoccerPlayer", b =>
                {
                    b.HasOne("HW__10_Advanced_databases_with_EF_Core.Models.SoccerTeam", "SoccerTeam")
                        .WithMany("Players")
                        .HasForeignKey("SoccerTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoccerTeam");
                });

            modelBuilder.Entity("HW__10_Advanced_databases_with_EF_Core.Models.SoccerTeam", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
